repos:
  - repo: local
    hooks:
      - id: black
        name: Format Python code with Black
        description: This hook formats Python code using Black.
        entry: black
        language: system
        files: '\.py$'
