repos:
  - repo: local
    hooks:
      - id: black
        name: Format Python code with Black
        description: This hook formats Python code using Black.
        entry: black
        language: system
        files: '\.py$'
      - id: conventional-pre-commit
        entry: conventional-pre-commit
        name: Conventional Pre-commit Hook
        description: This hook enforces conventional commit message format.
        stages: [commit-msg]
        args: [--strict, feat, fix, chore, test, custom, refactor, docs, bump]
        language: system
